### ISSUE TITLE
Provider Service interaction not matching correctly URLs

### ISSUE THREAD

**Issue by vaptsarov** [seek-oss/seek.automation.phantom#1]
First and foremost i would like to thank you for creating this service simulator :) 

About the issue :

## Description
When interactions paths are starting with the same URI, but after somepoint are different, only the first StartsWith match will be used.

## Steps to reproduce
1. Simulate pact service with the following pact 
```json
{
  "provider": {
    "name": "XXX Controller"
  },
  "consumer": {
    "name": "YYY"
  },
  "interactions": [
    {
      "description": "A post request for creating a new app type version",
      "provider_state": "Create new version 1.0",
      "request": {
        "method": "post",
        "path": "/app-versions/TestAppType/1.0"
      },
      "response": {
        "status": 201
      }
    },
    {
      "description": "A get request for retrieving a newly registered app type versions",
      "provider_state": "Get versions for 1.0 and 2.0",
      "request": {
        "method": "get",
        "path": "/app-versions/TestAppType"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json; charset=utf-8"
        },
        "body": [
          "1.0",
          "2.0"
        ]
      }
    }
  ]
}
```

## Observed result 
Regardless of which of the two endpoints are called, only the first will match.

## Reason
Due to the following code line
```C#
 if (providerServiceInteraction.Request.Path.StartsWith(request.Url.LocalPath)) - line 52 in Helper.cs
```

I quickly patched with a more strict matcher 
```C#
 if (providerServiceInteraction.Request.Path.Equals(request.Url.LocalPath))
```

p.s. All tests are green.

**Comment by xlegalles** [comment]
We found the same issue

**Comment by b3hdad** [comment]
Sorry I haven't been receiving any emails about this since I left SEEK. I see if I can fix this.

**Comment by b3hdad** [comment]
Sorry for the delay. I just submitted a pull request to Seek with your fix. Thank you.

**Comment by b3hdad** [comment]
Done and merged.
